blueprints/notes/models.py
from extensions import db
from flask_login import UserMixin


class User(db.Model,UserMixin):

    __tablename__='user'

    user_id=db.Column(db.Integer,primary_key=True,autoincrement=True)
    username=db.Column(db.String(150),nullable=False,unique=True)
    password=db.Column(db.String(100),nullable=False,unique=False)

    notes=db.relationship('Note',backref='user',lazy=True)

    def get_id(self):
        return self.user_id 

    def __repr__(self):
        return f"<{self.user_id}:{self.username}>"
    
class Note(db.Model):

    __tablename__='note'

    note_id=db.Column(db.Integer,primary_key=True,autoincrement=True)
    user_id=db.Column(db.Integer,db.ForeignKey('user.user_id'),nullable=False)
    title=db.Column(db.String(100),nullable=False)
    note=db.Column(db.Text,nullable=False)

    def __repr__(self):
        return f"<{self.note_id}:{self.title}>"

blueprints/notes/routes.py
from flask import render_template,request,session,flash,redirect,url_for,send_from_directory,Blueprint
from flask_login import current_user,login_required
from blueprints.notes.models import Note
from extensions import db,bcrypt
import json
from sqlalchemy.exc import SQLAlchemyError
import os,uuid
from pathlib import Path

notes=Blueprint('notes',__name__,template_folder='templates')

@notes.route('/')
@login_required
def home():
    username=current_user.username
    notes=[
        (note.title,note.note,note.note_id) for note in current_user.notes
    ]
    return render_template('notes/home.html',notes=notes,name=username)

@notes.route('/add',methods=['GET','POST'])
@login_required
def add_note():
        notes=[]
        if request.method=='POST':
            if "file" in request.files:
                uploaded_file=request.files.get('file')
                if uploaded_file and uploaded_file.content_type=='application/json':
                    try:
                        uploaded_json_file=json.load(uploaded_file)
                        for task in uploaded_json_file:
                            title=task['title'].strip()
                            note_content=task['note'].strip()
                            notes.append(Note(user_id=current_user.user_id,title=title,note=note_content))
                            # new_note=Note(user_id=session.get('user_id'),title=title,note=note_content)
                            # db.session.add(new_note)
                            # db.session.commit()
                    
                    except json.JSONDecodeError:
                        flash('Invalid json format','error')
    
            title=request.form.get('title','').strip()
            note_content=request.form.get('note','').strip()
            if title!='' and note_content !='':
                notes.append(Note(user_id=current_user.user_id,title=title,note=note_content))

            try:
                db.session.add_all(notes)
                db.session.commit()
                flash(f'Successfully added {len(notes)} notes', 'success')
            except SQLAlchemyError as e:
                db.session.rollback()  # Always rollback on error to keep session clean
                flash('An error occurred while adding notes.', 'error')
                print(f"Database error: {e}")
            return redirect(url_for('notes.home'))

        return render_template('notes/add_note.html')

@notes.route('/download')
@login_required
def download():
        tasks_as_dict=[{'title':note.title,'note':note.note}for note in current_user.notes]
        
        curr_dir=Path(__file__).resolve().parent
        root_dir=curr_dir.parent.parent
        downloads_dir_path=root_dir/'downloads'
        if not downloads_dir_path.exists():
            downloads_dir_path.mkdir()
        file_name=f"{uuid.uuid4()}.json"
        file_path=(downloads_dir_path/file_name).absolute()
        with open(file_path,'w',encoding='utf-8') as j:
            json.dump(tasks_as_dict,j,indent=2)
            
        return render_template('notes/download_page.html',filename=file_name)

@notes.route('/download/<filename>')
@login_required
def downloadFile(filename):
    curr_dir=Path(__file__).resolve().parent
    root_dir=curr_dir.parent.parent
    downloads_dir_path=(root_dir/'downloads').absolute()
    return send_from_directory(str(downloads_dir_path),filename,as_attachment=True,download_name='task.json')    



@notes.route('/remove/<int:note_id>',methods=['DELETE'])
@login_required
def remove(note_id):
        try:
            note=Note.query.get(note_id)
            if note and note.user_id==current_user.user_id:
                db.session.delete(note)
                db.session.commit()
                flash('Successfully removed note')
            else:
                flash('Note not found or unauthorzied')
        except Exception as e:
            db.session.rollback()
            flash('Something went wrong during removing')
        return "note removed"
    

blueprints/notes/templates/notes/add_note.html
{% extends 'base.html' %}
{% block title %}
    {{super()}} Add Note
{% endblock title %}
{% block content %}
    {{super()}}
    <h2>Add Note</h2>
    <form  method="POST"  enctype="multipart/form-data">
        <label for="title">Enter Title:</label><input type="text" name="title"></input><br><br>
        <label for="note">Enter Note:</label><textarea name="note"></textarea>
        <h3>OR</h3>
        <p>Uppload JSON file of the tasks</p>
        <input type="file" name="file" accept="application/json">
        <br><br><button type="submit">Add Note</button>
    </form>
{% endblock content %}

blueprints/notes/templates/notes/download_page.html
{% extends 'base.html' %}
{% block title %}Download{% endblock title %}
{% block content %}
    {{super()}}
    <h1>Download JSON file</h1>
    <a href="{{ url_for('notes.downloadFile', filename=filename) }}">Download</a>
{% endblock content %}

blueprints/notes/templates/notes/home.html
{% extends 'base.html' %}
{% block title %}{{super()}}Home{% endblock %}
{% block content %}
    {{super()}}
    <header><h1>{{name}}'s Notes</h1></header>

    
    <ol>
        {% for title,note,id in notes %}
            <li><h3>{{title|capitalize_title}}</h3>
                <p style="white-space: pre-line;">{{ note }}</p><button onclick="deleteNote({{id}})">Remove</button>

            </li>
            {% else %}
                <h3>NO NOTES!!</h3> 
        {% endfor %}
    </ol>
    <button ><a href="{{url_for('notes.add_note')}}" id='add_link'style="text-decoration: none;">Add Note</a></button>
    {% if  notes  %}
        <button><a href="{{url_for('notes.download')}}" id="download_link" style="text-decoration: none;">Download as JSON file</a></button>
    {% endif %}
    <button ><a href="{{url_for('core.logout')}}" id='add_link' style="text-decoration: none;">Logout</a></button>
    
    <script type="text/javascript">
        async function deleteNote(id){
            try{
                let response = await fetch(`http://127.0.0.1:5000/notes/remove/${id}`,{method:'DELETE'})
                if (response.ok){
                    alert('removed note')
                    window.location.reload()
                    
                }
            }
            catch(err){
                alert('Something went wrong during removing')
            }
        }
    </script>
    
    

      
{% endblock %}